module.exports = [
  {
    "id": 35978583,
    "name": "acosh",
    "full_name": "sindresorhus/acosh",
    "html_url": "https://github.com/sindresorhus/acosh",
    "description": "ES6 Math.acosh() ponyfill",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/acosh",
    "homepage": null,
    "size": 116,
    "stargazers_count": 4,
    "watchers_count": 4,
    "language": "JavaScript",
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 22608988,
    "name": "alfred-simple",
    "full_name": "sindresorhus/alfred-simple",
    "html_url": "https://github.com/sindresorhus/alfred-simple",
    "description": "Simple theme for Alfred",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/alfred-simple",
    "homepage": null,
    "size": 1448,
    "stargazers_count": 60,
    "watchers_count": 60,
    "language": null,
    "forks_count": 2,
    "default_branch": "master"
  },
  {
    "id": 28916579,
    "name": "alpha-sort",
    "full_name": "sindresorhus/alpha-sort",
    "html_url": "https://github.com/sindresorhus/alpha-sort",
    "description": "Alphabetically sort an array of strings",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/alpha-sort",
    "homepage": null,
    "size": 202,
    "stargazers_count": 10,
    "watchers_count": 10,
    "language": "JavaScript",
    "forks_count": 2,
    "default_branch": "master"
  },
  {
    "id": 38368663,
    "name": "ama",
    "full_name": "sindresorhus/ama",
    "html_url": "https://github.com/sindresorhus/ama",
    "description": "Ask me anything!",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/ama",
    "homepage": "",
    "size": 195,
    "stargazers_count": 302,
    "watchers_count": 302,
    "language": null,
    "forks_count": 148,
    "default_branch": "master"
  },
  {
    "id": 38531345,
    "name": "amas",
    "full_name": "sindresorhus/amas",
    "html_url": "https://github.com/sindresorhus/amas",
    "description": "Awesome & Marvelous Amas",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/amas",
    "homepage": "",
    "size": 645,
    "stargazers_count": 263,
    "watchers_count": 263,
    "language": null,
    "forks_count": 70,
    "default_branch": "master"
  },
  {
    "id": 38837841,
    "name": "Android-DirectoryChooser",
    "full_name": "sindresorhus/Android-DirectoryChooser",
    "html_url": "https://github.com/sindresorhus/Android-DirectoryChooser",
    "description": "A directory chooser library for Android.",
    "fork": true,
    "url": "https://api.github.com/repos/sindresorhus/Android-DirectoryChooser",
    "homepage": null,
    "size": 10817,
    "stargazers_count": 2,
    "watchers_count": 2,
    "language": "Java",
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 38714150,
    "name": "android-lint-summary",
    "full_name": "sindresorhus/android-lint-summary",
    "html_url": "https://github.com/sindresorhus/android-lint-summary",
    "description": "Prettier display of Android Lint issues",
    "fork": true,
    "url": "https://api.github.com/repos/sindresorhus/android-lint-summary",
    "homepage": "https://passy.github.io/android-lint-summary",
    "size": 790,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Haskell",
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 40721875,
    "name": "ansi-escapes",
    "full_name": "sindresorhus/ansi-escapes",
    "html_url": "https://github.com/sindresorhus/ansi-escapes",
    "description": "ANSI escape codes for manipulating the terminal",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/ansi-escapes",
    "homepage": null,
    "size": 124,
    "stargazers_count": 15,
    "watchers_count": 15,
    "language": "JavaScript",
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 33655344,
    "name": "anybar",
    "full_name": "sindresorhus/anybar",
    "html_url": "https://github.com/sindresorhus/anybar",
    "description": "Node.js client for the AnyBar app",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/anybar",
    "homepage": null,
    "size": 132,
    "stargazers_count": 48,
    "watchers_count": 48,
    "language": "JavaScript",
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 33765025,
    "name": "AnyBar-1",
    "full_name": "sindresorhus/AnyBar-1",
    "html_url": "https://github.com/sindresorhus/AnyBar-1",
    "description": "OS X menubar status indicator",
    "fork": true,
    "url": "https://api.github.com/repos/sindresorhus/AnyBar-1",
    "homepage": null,
    "size": 779,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Objective-C",
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 35832484,
    "name": "app-path",
    "full_name": "sindresorhus/app-path",
    "html_url": "https://github.com/sindresorhus/app-path",
    "description": "Get the path to an app (OS X)",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/app-path",
    "homepage": null,
    "size": 233,
    "stargazers_count": 17,
    "watchers_count": 17,
    "language": "JavaScript",
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 39301839,
    "name": "app-path-cli",
    "full_name": "sindresorhus/app-path-cli",
    "html_url": "https://github.com/sindresorhus/app-path-cli",
    "description": "Get the path to an app (OS X)",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/app-path-cli",
    "homepage": null,
    "size": 120,
    "stargazers_count": 10,
    "watchers_count": 10,
    "language": "JavaScript",
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 14759244,
    "name": "appstore-symbols",
    "full_name": "sindresorhus/appstore-symbols",
    "html_url": "https://github.com/sindresorhus/appstore-symbols",
    "description": "List of symbols usable in an app description for the iOS App Store",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/appstore-symbols",
    "homepage": "",
    "size": 109,
    "stargazers_count": 12,
    "watchers_count": 12,
    "language": null,
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 35180884,
    "name": "appveyor-node",
    "full_name": "sindresorhus/appveyor-node",
    "html_url": "https://github.com/sindresorhus/appveyor-node",
    "description": "Boilerplate appveyor.yml file for running Node.js tests on AppVeyor",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/appveyor-node",
    "homepage": "",
    "size": 128,
    "stargazers_count": 16,
    "watchers_count": 16,
    "language": null,
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 35784269,
    "name": "archive-extensions",
    "full_name": "sindresorhus/archive-extensions",
    "html_url": "https://github.com/sindresorhus/archive-extensions",
    "description": "List of archive file extensions",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/archive-extensions",
    "homepage": null,
    "size": 116,
    "stargazers_count": 4,
    "watchers_count": 4,
    "language": "JavaScript",
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 28924886,
    "name": "archs",
    "full_name": "sindresorhus/archs",
    "html_url": "https://github.com/sindresorhus/archs",
    "description": "List of processor architectures supported by Node",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/archs",
    "homepage": null,
    "size": 144,
    "stargazers_count": 4,
    "watchers_count": 4,
    "language": "JavaScript",
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 40240281,
    "name": "are-feross-and-mafintosh-stuck-in-an-elevator",
    "full_name": "sindresorhus/are-feross-and-mafintosh-stuck-in-an-elevator",
    "html_url": "https://github.com/sindresorhus/are-feross-and-mafintosh-stuck-in-an-elevator",
    "description": "WIP - nothing to see here",
    "fork": true,
    "url": "https://api.github.com/repos/sindresorhus/are-feross-and-mafintosh-stuck-in-an-elevator",
    "homepage": null,
    "size": 94,
    "stargazers_count": 2,
    "watchers_count": 2,
    "language": "JavaScript",
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 41850000,
    "name": "arr-exclude",
    "full_name": "sindresorhus/arr-exclude",
    "html_url": "https://github.com/sindresorhus/arr-exclude",
    "description": "Exclude certain items from an array",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/arr-exclude",
    "homepage": null,
    "size": 130,
    "stargazers_count": 7,
    "watchers_count": 7,
    "language": "JavaScript",
    "forks_count": 1,
    "default_branch": "master"
  },
  {
    "id": 41850131,
    "name": "arr-include",
    "full_name": "sindresorhus/arr-include",
    "html_url": "https://github.com/sindresorhus/arr-include",
    "description": "Include only certain items in an array",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/arr-include",
    "homepage": null,
    "size": 128,
    "stargazers_count": 3,
    "watchers_count": 3,
    "language": "JavaScript",
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 21053509,
    "name": "array-differ",
    "full_name": "sindresorhus/array-differ",
    "html_url": "https://github.com/sindresorhus/array-differ",
    "description": "Create an array with values that are present in the first input array but not additional ones",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/array-differ",
    "homepage": null,
    "size": 156,
    "stargazers_count": 6,
    "watchers_count": 6,
    "language": "JavaScript",
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 41926959,
    "name": "array-move",
    "full_name": "sindresorhus/array-move",
    "html_url": "https://github.com/sindresorhus/array-move",
    "description": "Move an array item to a different position",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/array-move",
    "homepage": null,
    "size": 122,
    "stargazers_count": 14,
    "watchers_count": 14,
    "language": "JavaScript",
    "forks_count": 1,
    "default_branch": "master"
  },
  {
    "id": 20116579,
    "name": "array-shuffle",
    "full_name": "sindresorhus/array-shuffle",
    "html_url": "https://github.com/sindresorhus/array-shuffle",
    "description": "Randomize the order of items in an array",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/array-shuffle",
    "homepage": null,
    "size": 152,
    "stargazers_count": 16,
    "watchers_count": 16,
    "language": "JavaScript",
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 21005682,
    "name": "array-union",
    "full_name": "sindresorhus/array-union",
    "html_url": "https://github.com/sindresorhus/array-union",
    "description": "Create an array of unique values, in order, from the input arrays",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/array-union",
    "homepage": "",
    "size": 148,
    "stargazers_count": 7,
    "watchers_count": 7,
    "language": "JavaScript",
    "forks_count": 2,
    "default_branch": "master"
  },
  {
    "id": 20813838,
    "name": "array-uniq",
    "full_name": "sindresorhus/array-uniq",
    "html_url": "https://github.com/sindresorhus/array-uniq",
    "description": "Create an array without duplicates",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/array-uniq",
    "homepage": "",
    "size": 198,
    "stargazers_count": 12,
    "watchers_count": 12,
    "language": "JavaScript",
    "forks_count": 5,
    "default_branch": "master"
  },
  {
    "id": 30872807,
    "name": "arrify",
    "full_name": "sindresorhus/arrify",
    "html_url": "https://github.com/sindresorhus/arrify",
    "description": "Convert a value to an array",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/arrify",
    "homepage": null,
    "size": 123,
    "stargazers_count": 21,
    "watchers_count": 21,
    "language": "JavaScript",
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 16847174,
    "name": "article-title",
    "full_name": "sindresorhus/article-title",
    "html_url": "https://github.com/sindresorhus/article-title",
    "description": "Extract the article title of a HTML document",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/article-title",
    "homepage": null,
    "size": 364,
    "stargazers_count": 12,
    "watchers_count": 12,
    "language": "HTML",
    "forks_count": 2,
    "default_branch": "master"
  },
  {
    "id": 35979428,
    "name": "asinh",
    "full_name": "sindresorhus/asinh",
    "html_url": "https://github.com/sindresorhus/asinh",
    "description": "ES6 Math.asinh() ponyfill",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/asinh",
    "homepage": null,
    "size": 116,
    "stargazers_count": 2,
    "watchers_count": 2,
    "language": "JavaScript",
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 17230753,
    "name": "atom-autoprefixer",
    "full_name": "sindresorhus/atom-autoprefixer",
    "html_url": "https://github.com/sindresorhus/atom-autoprefixer",
    "description": "Prefix CSS with Autoprefixer",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/atom-autoprefixer",
    "homepage": "https://atom.io/packages/autoprefixer",
    "size": 275,
    "stargazers_count": 64,
    "watchers_count": 64,
    "language": "JavaScript",
    "forks_count": 3,
    "default_branch": "master"
  },
  {
    "id": 17411980,
    "name": "atom-editorconfig",
    "full_name": "sindresorhus/atom-editorconfig",
    "html_url": "https://github.com/sindresorhus/atom-editorconfig",
    "description": "Helps developers maintain consistent coding styles between different editors",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/atom-editorconfig",
    "homepage": "https://atom.io/packages/editorconfig",
    "size": 370,
    "stargazers_count": 214,
    "watchers_count": 214,
    "language": "JavaScript",
    "forks_count": 17,
    "default_branch": "master"
  },
  {
    "id": 24718813,
    "name": "atom-esformatter",
    "full_name": "sindresorhus/atom-esformatter",
    "html_url": "https://github.com/sindresorhus/atom-esformatter",
    "description": "Beautify JavaScript",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/atom-esformatter",
    "homepage": "https://atom.io/packages/esformatter",
    "size": 305,
    "stargazers_count": 70,
    "watchers_count": 70,
    "language": "JavaScript",
    "forks_count": 9,
    "default_branch": "master"
  },
  {
    "id": 24676900,
    "name": "atom-fixmyjs",
    "full_name": "sindresorhus/atom-fixmyjs",
    "html_url": "https://github.com/sindresorhus/atom-fixmyjs",
    "description": "Automagically fix JSHint lint warnings",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/atom-fixmyjs",
    "homepage": "https://atom.io/packages/fixmyjs",
    "size": 238,
    "stargazers_count": 79,
    "watchers_count": 79,
    "language": "JavaScript",
    "forks_count": 3,
    "default_branch": "master"
  },
  {
    "id": 37476904,
    "name": "atom-focus-dark",
    "full_name": "sindresorhus/atom-focus-dark",
    "html_url": "https://github.com/sindresorhus/atom-focus-dark",
    "description": "Syntax theme that lets you focus on the content",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/atom-focus-dark",
    "homepage": "https://atom.io/packages/focus-dark",
    "size": 260,
    "stargazers_count": 24,
    "watchers_count": 24,
    "language": "CSS",
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 37484026,
    "name": "atom-focus-light",
    "full_name": "sindresorhus/atom-focus-light",
    "html_url": "https://github.com/sindresorhus/atom-focus-light",
    "description": "Syntax theme that lets you focus on the content",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/atom-focus-light",
    "homepage": "https://atom.io/packages/focus-light",
    "size": 277,
    "stargazers_count": 14,
    "watchers_count": 14,
    "language": "CSS",
    "forks_count": 1,
    "default_branch": "master"
  },
  {
    "id": 17263538,
    "name": "atom-jshint",
    "full_name": "sindresorhus/atom-jshint",
    "html_url": "https://github.com/sindresorhus/atom-jshint",
    "description": "Validate JavaScript with JSHint",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/atom-jshint",
    "homepage": "https://atom.io/packages/jshint",
    "size": 875,
    "stargazers_count": 113,
    "watchers_count": 113,
    "language": "JavaScript",
    "forks_count": 28,
    "default_branch": "master"
  },
  {
    "id": 40055286,
    "name": "atom-linter-xo",
    "full_name": "sindresorhus/atom-linter-xo",
    "html_url": "https://github.com/sindresorhus/atom-linter-xo",
    "description": "Linter for XO",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/atom-linter-xo",
    "homepage": null,
    "size": 205,
    "stargazers_count": 20,
    "watchers_count": 20,
    "language": "JavaScript",
    "forks_count": 1,
    "default_branch": "master"
  },
  {
    "id": 42105988,
    "name": "atom-perfectionist",
    "full_name": "sindresorhus/atom-perfectionist",
    "html_url": "https://github.com/sindresorhus/atom-perfectionist",
    "description": "Beautify CSS",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/atom-perfectionist",
    "homepage": "https://atom.io/packages/perfectionist",
    "size": 92,
    "stargazers_count": 11,
    "watchers_count": 11,
    "language": "JavaScript",
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 17265079,
    "name": "atom-uglify",
    "full_name": "sindresorhus/atom-uglify",
    "html_url": "https://github.com/sindresorhus/atom-uglify",
    "description": "Minify JavaScript",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/atom-uglify",
    "homepage": "https://atom.io/packages/uglify",
    "size": 182,
    "stargazers_count": 13,
    "watchers_count": 13,
    "language": "JavaScript",
    "forks_count": 2,
    "default_branch": "master"
  },
  {
    "id": 26820798,
    "name": "ava",
    "full_name": "sindresorhus/ava",
    "html_url": "https://github.com/sindresorhus/ava",
    "description": "Simple concurrent test runner",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/ava",
    "homepage": "",
    "size": 3378,
    "stargazers_count": 399,
    "watchers_count": 399,
    "language": "JavaScript",
    "forks_count": 13,
    "default_branch": "master"
  },
  {
    "id": 41851103,
    "name": "ava-init",
    "full_name": "sindresorhus/ava-init",
    "html_url": "https://github.com/sindresorhus/ava-init",
    "description": "Add AVA to your project",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/ava-init",
    "homepage": "http://ava.li",
    "size": 156,
    "stargazers_count": 8,
    "watchers_count": 8,
    "language": "JavaScript",
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 21737465,
    "name": "awesome",
    "full_name": "sindresorhus/awesome",
    "html_url": "https://github.com/sindresorhus/awesome",
    "description": "A curated list of awesome lists",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/awesome",
    "homepage": "",
    "size": 1949,
    "stargazers_count": 18489,
    "watchers_count": 18489,
    "language": null,
    "forks_count": 1900,
    "default_branch": "master"
  },
  {
    "id": 41553741,
    "name": "awesome-AutoHotkey",
    "full_name": "sindresorhus/awesome-AutoHotkey",
    "html_url": "https://github.com/sindresorhus/awesome-AutoHotkey",
    "description": "A curated list of awesome AutoHotkey libraries, library distributions, scripts, tools and resources.",
    "fork": true,
    "url": "https://api.github.com/repos/sindresorhus/awesome-AutoHotkey",
    "homepage": "https://ahkscript.github.io/awesome-AutoHotkey",
    "size": 209,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": null,
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 21794671,
    "name": "awesome-awesome-awesome-awesome",
    "full_name": "sindresorhus/awesome-awesome-awesome-awesome",
    "html_url": "https://github.com/sindresorhus/awesome-awesome-awesome-awesome",
    "description": "A curated list of awesome lists of awesome lists.",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/awesome-awesome-awesome-awesome",
    "homepage": null,
    "size": 140,
    "stargazers_count": 24,
    "watchers_count": 24,
    "language": null,
    "forks_count": 1,
    "default_branch": "master"
  },
  {
    "id": 29865323,
    "name": "awesome-awesomeness",
    "full_name": "sindresorhus/awesome-awesomeness",
    "html_url": "https://github.com/sindresorhus/awesome-awesomeness",
    "description": "A curated list of awesome awesomeness",
    "fork": true,
    "url": "https://api.github.com/repos/sindresorhus/awesome-awesomeness",
    "homepage": "",
    "size": 146,
    "stargazers_count": 1,
    "watchers_count": 1,
    "language": null,
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 34453060,
    "name": "awesome-electron",
    "full_name": "sindresorhus/awesome-electron",
    "html_url": "https://github.com/sindresorhus/awesome-electron",
    "description": "Useful resources for creating apps with Electron",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/awesome-electron",
    "homepage": "",
    "size": 729,
    "stargazers_count": 2437,
    "watchers_count": 2437,
    "language": null,
    "forks_count": 132,
    "default_branch": "master"
  },
  {
    "id": 21737266,
    "name": "awesome-nodejs",
    "full_name": "sindresorhus/awesome-nodejs",
    "html_url": "https://github.com/sindresorhus/awesome-nodejs",
    "description": "A curated list of delightful Node.js packages and resources.",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/awesome-nodejs",
    "homepage": null,
    "size": 2366,
    "stargazers_count": 8352,
    "watchers_count": 8352,
    "language": null,
    "forks_count": 845,
    "default_branch": "master"
  },
  {
    "id": 42294996,
    "name": "awesome-osx",
    "full_name": "sindresorhus/awesome-osx",
    "html_url": "https://github.com/sindresorhus/awesome-osx",
    "description": ":memo: A curated list of awesome applications, softwares, tools and shiny things for OS X.",
    "fork": true,
    "url": "https://api.github.com/repos/sindresorhus/awesome-osx",
    "homepage": "",
    "size": 357,
    "stargazers_count": 18,
    "watchers_count": 18,
    "language": null,
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 39962375,
    "name": "awesome-purescript",
    "full_name": "sindresorhus/awesome-purescript",
    "html_url": "https://github.com/sindresorhus/awesome-purescript",
    "description": "A curation of awesome PureScript libraries, resources and shiny things.",
    "fork": true,
    "url": "https://api.github.com/repos/sindresorhus/awesome-purescript",
    "homepage": null,
    "size": 87,
    "stargazers_count": 1,
    "watchers_count": 1,
    "language": null,
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 29582583,
    "name": "awesome-scifi",
    "full_name": "sindresorhus/awesome-scifi",
    "html_url": "https://github.com/sindresorhus/awesome-scifi",
    "description": "Sci-Fi worth consuming",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/awesome-scifi",
    "homepage": null,
    "size": 1747,
    "stargazers_count": 797,
    "watchers_count": 797,
    "language": null,
    "forks_count": 59,
    "default_branch": "master"
  },
  {
    "id": 30873008,
    "name": "babel",
    "full_name": "sindresorhus/babel",
    "html_url": "https://github.com/sindresorhus/babel",
    "description": "Babel is a transpiler for writing next generation JavaScript. (Previously 6to5)",
    "fork": true,
    "url": "https://api.github.com/repos/sindresorhus/babel",
    "homepage": "https://babeljs.io/",
    "size": 3608,
    "stargazers_count": 1,
    "watchers_count": 1,
    "language": "JavaScript",
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 36136824,
    "name": "babel-sublime",
    "full_name": "sindresorhus/babel-sublime",
    "html_url": "https://github.com/sindresorhus/babel-sublime",
    "description": "Syntax definitions for ES6 JavaScript with React JSX extensions.",
    "fork": true,
    "url": "https://api.github.com/repos/sindresorhus/babel-sublime",
    "homepage": "https://babeljs.io/",
    "size": 881,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 27369198,
    "name": "beeper",
    "full_name": "sindresorhus/beeper",
    "html_url": "https://github.com/sindresorhus/beeper",
    "description": "Make your terminal beep",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/beeper",
    "homepage": null,
    "size": 1213,
    "stargazers_count": 58,
    "watchers_count": 58,
    "language": "JavaScript",
    "forks_count": 4,
    "default_branch": "master"
  },
  {
    "id": 20841967,
    "name": "bin-version",
    "full_name": "sindresorhus/bin-version",
    "html_url": "https://github.com/sindresorhus/bin-version",
    "description": "Get the version of a binary in semver format",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/bin-version",
    "homepage": null,
    "size": 166,
    "stargazers_count": 3,
    "watchers_count": 3,
    "language": "JavaScript",
    "forks_count": 2,
    "default_branch": "master"
  },
  {
    "id": 20842060,
    "name": "bin-version-check",
    "full_name": "sindresorhus/bin-version-check",
    "html_url": "https://github.com/sindresorhus/bin-version-check",
    "description": "Check whether a binary version satisfies a semver range",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/bin-version-check",
    "homepage": null,
    "size": 196,
    "stargazers_count": 3,
    "watchers_count": 3,
    "language": "JavaScript",
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 29771015,
    "name": "binary-extensions",
    "full_name": "sindresorhus/binary-extensions",
    "html_url": "https://github.com/sindresorhus/binary-extensions",
    "description": "List of binary file extensions",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/binary-extensions",
    "homepage": null,
    "size": 282,
    "stargazers_count": 16,
    "watchers_count": 16,
    "language": "JavaScript",
    "forks_count": 2,
    "default_branch": "master"
  },
  {
    "id": 36266335,
    "name": "blear",
    "full_name": "sindresorhus/blear",
    "html_url": "https://github.com/sindresorhus/blear",
    "description": "Landing page for the Blear app",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/blear",
    "homepage": "http://sindresorhus.com/blear",
    "size": 1239,
    "stargazers_count": 16,
    "watchers_count": 16,
    "language": "CSS",
    "forks_count": 2,
    "default_branch": "gh-pages"
  },
  {
    "id": 5814528,
    "name": "bower-components",
    "full_name": "sindresorhus/bower-components",
    "html_url": "https://github.com/sindresorhus/bower-components",
    "description": "[deprecated] Site to discover Bower components",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/bower-components",
    "homepage": "",
    "size": 1394,
    "stargazers_count": 233,
    "watchers_count": 233,
    "language": "CSS",
    "forks_count": 57,
    "default_branch": "master"
  },
  {
    "id": 18737175,
    "name": "bower-name",
    "full_name": "sindresorhus/bower-name",
    "html_url": "https://github.com/sindresorhus/bower-name",
    "description": "Check whether a package name is available on bower",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/bower-name",
    "homepage": null,
    "size": 159,
    "stargazers_count": 4,
    "watchers_count": 4,
    "language": "JavaScript",
    "forks_count": 1,
    "default_branch": "master"
  },
  {
    "id": 16922097,
    "name": "broccoli-autoprefixer",
    "full_name": "sindresorhus/broccoli-autoprefixer",
    "html_url": "https://github.com/sindresorhus/broccoli-autoprefixer",
    "description": "Prefix CSS using Autoprefixer",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/broccoli-autoprefixer",
    "homepage": null,
    "size": 304,
    "stargazers_count": 23,
    "watchers_count": 23,
    "language": "JavaScript",
    "forks_count": 7,
    "default_branch": "master"
  },
  {
    "id": 17040354,
    "name": "broccoli-closure-compiler",
    "full_name": "sindresorhus/broccoli-closure-compiler",
    "html_url": "https://github.com/sindresorhus/broccoli-closure-compiler",
    "description": "Minify JavaScript with Closure Compiler",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/broccoli-closure-compiler",
    "homepage": null,
    "size": 154,
    "stargazers_count": 7,
    "watchers_count": 7,
    "language": "JavaScript",
    "forks_count": 1,
    "default_branch": "master"
  },
  {
    "id": 34042819,
    "name": "broccoli-cssnano",
    "full_name": "sindresorhus/broccoli-cssnano",
    "html_url": "https://github.com/sindresorhus/broccoli-cssnano",
    "description": "Minify CSS",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/broccoli-cssnano",
    "homepage": null,
    "size": 176,
    "stargazers_count": 6,
    "watchers_count": 6,
    "language": "JavaScript",
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 16922683,
    "name": "broccoli-csso",
    "full_name": "sindresorhus/broccoli-csso",
    "html_url": "https://github.com/sindresorhus/broccoli-csso",
    "description": "Minimize CSS using CSSO",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/broccoli-csso",
    "homepage": null,
    "size": 183,
    "stargazers_count": 6,
    "watchers_count": 6,
    "language": "JavaScript",
    "forks_count": 2,
    "default_branch": "master"
  },
  {
    "id": 17074721,
    "name": "broccoli-defeatureify",
    "full_name": "sindresorhus/broccoli-defeatureify",
    "html_url": "https://github.com/sindresorhus/broccoli-defeatureify",
    "description": "Remove specially flagged feature blocks and debug statements using Defeatureify",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/broccoli-defeatureify",
    "homepage": null,
    "size": 387,
    "stargazers_count": 5,
    "watchers_count": 5,
    "language": "JavaScript",
    "forks_count": 4,
    "default_branch": "master"
  },
  {
    "id": 17155018,
    "name": "broccoli-dust",
    "full_name": "sindresorhus/broccoli-dust",
    "html_url": "https://github.com/sindresorhus/broccoli-dust",
    "description": "Precompile Dust templates",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/broccoli-dust",
    "homepage": null,
    "size": 154,
    "stargazers_count": 5,
    "watchers_count": 5,
    "language": "JavaScript",
    "forks_count": 1,
    "default_branch": "master"
  },
  {
    "id": 17154293,
    "name": "broccoli-es6-transpiler",
    "full_name": "sindresorhus/broccoli-es6-transpiler",
    "html_url": "https://github.com/sindresorhus/broccoli-es6-transpiler",
    "description": "Transpile ES6 to ES5",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/broccoli-es6-transpiler",
    "homepage": null,
    "size": 192,
    "stargazers_count": 10,
    "watchers_count": 10,
    "language": "JavaScript",
    "forks_count": 2,
    "default_branch": "master"
  },
  {
    "id": 16924257,
    "name": "broccoli-htmlmin",
    "full_name": "sindresorhus/broccoli-htmlmin",
    "html_url": "https://github.com/sindresorhus/broccoli-htmlmin",
    "description": "Minify HTML",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/broccoli-htmlmin",
    "homepage": null,
    "size": 209,
    "stargazers_count": 4,
    "watchers_count": 4,
    "language": "JavaScript",
    "forks_count": 1,
    "default_branch": "master"
  },
  {
    "id": 16924987,
    "name": "broccoli-jade",
    "full_name": "sindresorhus/broccoli-jade",
    "html_url": "https://github.com/sindresorhus/broccoli-jade",
    "description": "Compile Jade templates",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/broccoli-jade",
    "homepage": null,
    "size": 271,
    "stargazers_count": 6,
    "watchers_count": 6,
    "language": "JavaScript",
    "forks_count": 6,
    "default_branch": "master"
  },
  {
    "id": 16926258,
    "name": "broccoli-less",
    "full_name": "sindresorhus/broccoli-less",
    "html_url": "https://github.com/sindresorhus/broccoli-less",
    "description": "Compile LESS",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/broccoli-less",
    "homepage": null,
    "size": 163,
    "stargazers_count": 12,
    "watchers_count": 12,
    "language": "JavaScript",
    "forks_count": 2,
    "default_branch": "master"
  },
  {
    "id": 17155183,
    "name": "broccoli-nunjucks",
    "full_name": "sindresorhus/broccoli-nunjucks",
    "html_url": "https://github.com/sindresorhus/broccoli-nunjucks",
    "description": "Precompile Nunjucks templates",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/broccoli-nunjucks",
    "homepage": null,
    "size": 155,
    "stargazers_count": 3,
    "watchers_count": 3,
    "language": "JavaScript",
    "forks_count": 1,
    "default_branch": "master"
  },
  {
    "id": 17040343,
    "name": "broccoli-regenerator",
    "full_name": "sindresorhus/broccoli-regenerator",
    "html_url": "https://github.com/sindresorhus/broccoli-regenerator",
    "description": "Transpile ES6 generator functions to ES5",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/broccoli-regenerator",
    "homepage": null,
    "size": 198,
    "stargazers_count": 6,
    "watchers_count": 6,
    "language": "JavaScript",
    "forks_count": 2,
    "default_branch": "master"
  },
  {
    "id": 25608058,
    "name": "broccoli-strip-css-comments",
    "full_name": "sindresorhus/broccoli-strip-css-comments",
    "html_url": "https://github.com/sindresorhus/broccoli-strip-css-comments",
    "description": "Strip comments from CSS",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/broccoli-strip-css-comments",
    "homepage": null,
    "size": 168,
    "stargazers_count": 1,
    "watchers_count": 1,
    "language": "JavaScript",
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 17098508,
    "name": "broccoli-strip-debug",
    "full_name": "sindresorhus/broccoli-strip-debug",
    "html_url": "https://github.com/sindresorhus/broccoli-strip-debug",
    "description": "Strip console, alert, and debugger statements from JavaScript code",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/broccoli-strip-debug",
    "homepage": "https://github.com/sindresorhus/strip-debug",
    "size": 171,
    "stargazers_count": 7,
    "watchers_count": 7,
    "language": "JavaScript",
    "forks_count": 1,
    "default_branch": "master"
  },
  {
    "id": 17154718,
    "name": "broccoli-strip-json-comments",
    "full_name": "sindresorhus/broccoli-strip-json-comments",
    "html_url": "https://github.com/sindresorhus/broccoli-strip-json-comments",
    "description": "Strip comments from JSON. Lets you use comments in your JSON files!",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/broccoli-strip-json-comments",
    "homepage": null,
    "size": 166,
    "stargazers_count": 4,
    "watchers_count": 4,
    "language": "JavaScript",
    "forks_count": 1,
    "default_branch": "master"
  },
  {
    "id": 17019218,
    "name": "broccoli-stylus",
    "full_name": "sindresorhus/broccoli-stylus",
    "html_url": "https://github.com/sindresorhus/broccoli-stylus",
    "description": "Compile Stylus",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/broccoli-stylus",
    "homepage": null,
    "size": 214,
    "stargazers_count": 6,
    "watchers_count": 6,
    "language": "JavaScript",
    "forks_count": 6,
    "default_branch": "master"
  },
  {
    "id": 16923435,
    "name": "broccoli-svgo",
    "full_name": "sindresorhus/broccoli-svgo",
    "html_url": "https://github.com/sindresorhus/broccoli-svgo",
    "description": "Minimize SVG using SVGO",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/broccoli-svgo",
    "homepage": null,
    "size": 209,
    "stargazers_count": 4,
    "watchers_count": 4,
    "language": "JavaScript",
    "forks_count": 1,
    "default_branch": "master"
  },
  {
    "id": 17025138,
    "name": "broccoli-sweetjs",
    "full_name": "sindresorhus/broccoli-sweetjs",
    "html_url": "https://github.com/sindresorhus/broccoli-sweetjs",
    "description": "Transpile Sweet.js macros",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/broccoli-sweetjs",
    "homepage": null,
    "size": 268,
    "stargazers_count": 10,
    "watchers_count": 10,
    "language": "JavaScript",
    "forks_count": 4,
    "default_branch": "master"
  },
  {
    "id": 17019941,
    "name": "broccoli-traceur",
    "full_name": "sindresorhus/broccoli-traceur",
    "html_url": "https://github.com/sindresorhus/broccoli-traceur",
    "description": "Traceur is a JavaScript.next to JavaScript-of-today compiler",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/broccoli-traceur",
    "homepage": null,
    "size": 298,
    "stargazers_count": 28,
    "watchers_count": 28,
    "language": "JavaScript",
    "forks_count": 9,
    "default_branch": "master"
  },
  {
    "id": 16925775,
    "name": "broccoli-uncss",
    "full_name": "sindresorhus/broccoli-uncss",
    "html_url": "https://github.com/sindresorhus/broccoli-uncss",
    "description": "Remove unused CSS with UnCSS",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/broccoli-uncss",
    "homepage": null,
    "size": 211,
    "stargazers_count": 21,
    "watchers_count": 21,
    "language": "JavaScript",
    "forks_count": 2,
    "default_branch": "master"
  },
  {
    "id": 35334447,
    "name": "buf-compare",
    "full_name": "sindresorhus/buf-compare",
    "html_url": "https://github.com/sindresorhus/buf-compare",
    "description": "Node.js 0.12 Buffer.compare() ponyfill",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/buf-compare",
    "homepage": null,
    "size": 124,
    "stargazers_count": 5,
    "watchers_count": 5,
    "language": "JavaScript",
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 35334341,
    "name": "buf-indexof",
    "full_name": "sindresorhus/buf-indexof",
    "html_url": "https://github.com/sindresorhus/buf-indexof",
    "description": "io.js 1.5.0 (Node.js) buffer.indexOf() ponyfill",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/buf-indexof",
    "homepage": null,
    "size": 120,
    "stargazers_count": 3,
    "watchers_count": 3,
    "language": "JavaScript",
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 34901807,
    "name": "buffer-equals",
    "full_name": "sindresorhus/buffer-equals",
    "html_url": "https://github.com/sindresorhus/buffer-equals",
    "description": "Node.js 0.12 buffer.equals() ponyfill",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/buffer-equals",
    "homepage": null,
    "size": 156,
    "stargazers_count": 6,
    "watchers_count": 6,
    "language": "JavaScript",
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 35040648,
    "name": "builtin-modules",
    "full_name": "sindresorhus/builtin-modules",
    "html_url": "https://github.com/sindresorhus/builtin-modules",
    "description": "List of the Node.js builtin modules",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/builtin-modules",
    "homepage": null,
    "size": 148,
    "stargazers_count": 5,
    "watchers_count": 5,
    "language": "JavaScript",
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 16633552,
    "name": "bundle-id",
    "full_name": "sindresorhus/bundle-id",
    "html_url": "https://github.com/sindresorhus/bundle-id",
    "description": "Get bundle identifier from a bundle name (OS X): Safari → com.apple.Safari",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/bundle-id",
    "homepage": "",
    "size": 180,
    "stargazers_count": 5,
    "watchers_count": 5,
    "language": "JavaScript",
    "forks_count": 1,
    "default_branch": "master"
  },
  {
    "id": 16289922,
    "name": "bundle-name",
    "full_name": "sindresorhus/bundle-name",
    "html_url": "https://github.com/sindresorhus/bundle-name",
    "description": "Get bundle name from a bundle identifier (OS X): com.apple.Safari → Safari",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/bundle-name",
    "homepage": "",
    "size": 183,
    "stargazers_count": 2,
    "watchers_count": 2,
    "language": "JavaScript",
    "forks_count": 1,
    "default_branch": "master"
  },
  {
    "id": 29782297,
    "name": "caller-callsite",
    "full_name": "sindresorhus/caller-callsite",
    "html_url": "https://github.com/sindresorhus/caller-callsite",
    "description": "Get the callsite of the caller function",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/caller-callsite",
    "homepage": null,
    "size": 151,
    "stargazers_count": 12,
    "watchers_count": 12,
    "language": "JavaScript",
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 18938832,
    "name": "caller-path",
    "full_name": "sindresorhus/caller-path",
    "html_url": "https://github.com/sindresorhus/caller-path",
    "description": "Get the path of the caller module",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/caller-path",
    "homepage": null,
    "size": 168,
    "stargazers_count": 4,
    "watchers_count": 4,
    "language": "JavaScript",
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 18938743,
    "name": "callsites",
    "full_name": "sindresorhus/callsites",
    "html_url": "https://github.com/sindresorhus/callsites",
    "description": "Get callsites from the V8 stack trace API",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/callsites",
    "homepage": null,
    "size": 160,
    "stargazers_count": 14,
    "watchers_count": 14,
    "language": "JavaScript",
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 25116836,
    "name": "camelcase",
    "full_name": "sindresorhus/camelcase",
    "html_url": "https://github.com/sindresorhus/camelcase",
    "description": "Convert a dash/dot/underscore/space separated string to camelCase: foo-bar → fooBar",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/camelcase",
    "homepage": "",
    "size": 203,
    "stargazers_count": 30,
    "watchers_count": 30,
    "language": "JavaScript",
    "forks_count": 2,
    "default_branch": "master"
  },
  {
    "id": 25118495,
    "name": "camelcase-keys",
    "full_name": "sindresorhus/camelcase-keys",
    "html_url": "https://github.com/sindresorhus/camelcase-keys",
    "description": "Convert object keys to camelCase",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/camelcase-keys",
    "homepage": null,
    "size": 140,
    "stargazers_count": 7,
    "watchers_count": 7,
    "language": "JavaScript",
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 42574339,
    "name": "caprine",
    "full_name": "sindresorhus/caprine",
    "html_url": "https://github.com/sindresorhus/caprine",
    "description": "Unofficial Facebook Messenger app",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/caprine",
    "homepage": null,
    "size": 1650,
    "stargazers_count": 361,
    "watchers_count": 361,
    "language": "JavaScript",
    "forks_count": 14,
    "default_branch": "master"
  },
  {
    "id": 29253090,
    "name": "cat-names",
    "full_name": "sindresorhus/cat-names",
    "html_url": "https://github.com/sindresorhus/cat-names",
    "description": "Get popular cat names",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/cat-names",
    "homepage": null,
    "size": 344,
    "stargazers_count": 51,
    "watchers_count": 51,
    "language": "JavaScript",
    "forks_count": 4,
    "default_branch": "master"
  },
  {
    "id": 35980257,
    "name": "cbrt",
    "full_name": "sindresorhus/cbrt",
    "html_url": "https://github.com/sindresorhus/cbrt",
    "description": "ES6 Math.cbrt() ponyfill",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/cbrt",
    "homepage": null,
    "size": 116,
    "stargazers_count": 2,
    "watchers_count": 2,
    "language": "JavaScript",
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 36388624,
    "name": "chakra-nerp",
    "full_name": "sindresorhus/chakra-nerp",
    "html_url": "https://github.com/sindresorhus/chakra-nerp",
    "description": "Prevent your code from being run in the Chakra JavaScript engine",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/chakra-nerp",
    "homepage": null,
    "size": 116,
    "stargazers_count": 11,
    "watchers_count": 11,
    "language": "JavaScript",
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 36068019,
    "name": "child-process-ctor",
    "full_name": "sindresorhus/child-process-ctor",
    "html_url": "https://github.com/sindresorhus/child-process-ctor",
    "description": "io.js 2.2.0 childProcess.ChildProcess ponyfill",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/child-process-ctor",
    "homepage": "",
    "size": 144,
    "stargazers_count": 3,
    "watchers_count": 3,
    "language": "JavaScript",
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 22521189,
    "name": "clear-downloads",
    "full_name": "sindresorhus/clear-downloads",
    "html_url": "https://github.com/sindresorhus/clear-downloads",
    "description": "Chrome extension - Clears the Downloads list every 10 seconds to force the download bar to disappear when all downloads are complete",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/clear-downloads",
    "homepage": "https://chrome.google.com/webstore/detail/clear-downloads/bknoejjhcfmakcibhifepfkegpjdnadk",
    "size": 156,
    "stargazers_count": 20,
    "watchers_count": 20,
    "language": "JavaScript",
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 22020501,
    "name": "clear-require",
    "full_name": "sindresorhus/clear-require",
    "html_url": "https://github.com/sindresorhus/clear-require",
    "description": "Clear a module from the require cache",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/clear-require",
    "homepage": null,
    "size": 156,
    "stargazers_count": 12,
    "watchers_count": 12,
    "language": "JavaScript",
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 23512396,
    "name": "cli-cursor",
    "full_name": "sindresorhus/cli-cursor",
    "html_url": "https://github.com/sindresorhus/cli-cursor",
    "description": "Toggle the CLI cursor",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/cli-cursor",
    "homepage": null,
    "size": 163,
    "stargazers_count": 10,
    "watchers_count": 10,
    "language": "JavaScript",
    "forks_count": 1,
    "default_branch": "master"
  },
  {
    "id": 18860721,
    "name": "clone-regexp",
    "full_name": "sindresorhus/clone-regexp",
    "html_url": "https://github.com/sindresorhus/clone-regexp",
    "description": "Clone and modify a RegExp instance",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/clone-regexp",
    "homepage": null,
    "size": 184,
    "stargazers_count": 10,
    "watchers_count": 10,
    "language": "JavaScript",
    "forks_count": 1,
    "default_branch": "master"
  },
  {
    "id": 35980980,
    "name": "clz32",
    "full_name": "sindresorhus/clz32",
    "html_url": "https://github.com/sindresorhus/clz32",
    "description": "ES6 Math.clz32() ponyfill",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/clz32",
    "homepage": null,
    "size": 116,
    "stargazers_count": 4,
    "watchers_count": 4,
    "language": "JavaScript",
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 39222010,
    "name": "code-point-at",
    "full_name": "sindresorhus/code-point-at",
    "html_url": "https://github.com/sindresorhus/code-point-at",
    "description": "ES2015 String#codePointAt() ponyfill",
    "fork": false,
    "url": "https://api.github.com/repos/sindresorhus/code-point-at",
    "homepage": null,
    "size": 115,
    "stargazers_count": 4,
    "watchers_count": 4,
    "language": "JavaScript",
    "forks_count": 0,
    "default_branch": "master"
  },
  {
    "id": 39667387,
    "name": "color-convert",
    "full_name": "sindresorhus/color-convert",
    "html_url": "https://github.com/sindresorhus/color-convert",
    "description": "Plain color conversion functions in JavaScript",
    "fork": true,
    "url": "https://api.github.com/repos/sindresorhus/color-convert",
    "homepage": "",
    "size": 137,
    "stargazers_count": 1,
    "watchers_count": 1,
    "language": "JavaScript",
    "forks_count": 0,
    "default_branch": "master"
  }
]